"""API key management for Amplifier."""

import os
import platform
from pathlib import Path


class KeyManager:
    """Manage API keys in ~/.amplifier/keys.env file."""

    def __init__(self):
        self.keys_file = Path.home() / ".amplifier" / "keys.env"
        self._load_keys()

    def _load_keys(self):
        """Load keys from file into environment if they exist."""
        if not self.keys_file.exists():
            return

        try:
            with open(self.keys_file, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        key = key.strip()  # Strip whitespace from key name
                        # Only set if not already in environment
                        if key not in os.environ:
                            os.environ[key] = value.strip().strip('"').strip("'")
        except Exception:
            # Fail silently - manual env vars will still work
            pass

    def has_key(self, key_name: str) -> bool:
        """Check if API key exists (in env or file)."""
        return key_name in os.environ

    def save_key(self, key_name: str, key_value: str) -> None:
        """Save API key to keys.env file securely."""
        self.keys_file.parent.mkdir(parents=True, exist_ok=True)

        # Read existing keys
        existing_keys = {}
        if self.keys_file.exists():
            with open(self.keys_file, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        k, v = line.split("=", 1)
                        existing_keys[k.strip()] = v

        # Update with new key
        existing_keys[key_name] = f'"{key_value}"'

        # Write back
        with open(self.keys_file, "w", encoding="utf-8") as f:
            f.write("# Amplifier API Keys\n")
            f.write("# Auto-generated by amplifier init or amplifier provider use\n")
            f.write("# These are loaded automatically on startup\n\n")
            for k, v in existing_keys.items():
                f.write(f"{k}={v}\n")

        # Set secure permissions (owner read/write only)
        # Skip on Windows where NTFS already restricts file permissions to the user
        if platform.system() != "Windows":
            self.keys_file.chmod(0o600)

        # Also set in current environment
        os.environ[key_name] = key_value
